spring.application.name=EcommerceApi

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=VGhpcy1Jcy1BLVZlcnktU3Ryb25nLUtleS1Gb3ItV1MxMDEtSldULUF1dGg=
jwt.expiration=86400000